[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:redis]
command=redis-server --protected-mode no
autostart=true
autorestart=true
stdout_logfile=/var/log/redis.log
stderr_logfile=/var/log/redis.err

[program:fastapi]
command=uvicorn backend.app.main:app --host 127.0.0.1 --port 8000 --workers 1
directory=/app
environment=PYTHONPATH="/app",INGEST_SOURCE="kafka",REDIS_HOST="127.0.0.1",REDIS_PORT="6379",CLICKHOUSE_HOST="127.0.0.1"
autostart=true
autorestart=true
stdout_logfile=/var/log/fastapi.log
stderr_logfile=/var/log/fastapi.err

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx.err
